### ISSUE TITLE
Provide a more exhaustive list of methods to download data

### ISSUE THREAD

**Issue by yarikoptic** [dandi/handbook#133]
Triggered by @TheChymera 

By default we just tell people to use `dandi` CLI. But there are also

- datalad datasets
- webdav interface
  - allows for a very unified access to the entire archive -- people could in principle `wget` entire archive.  For an individual  release eg.  `wget -r -nH --cut-dirs=3 --no-parent --reject "index.html*" https://webdav.dandiarchive.org/dandisets/000027/releases/0.210831.2033/`

**Comment by TheChymera** [comment]
Two issues:

1. `wget -r -nH --cut-dirs=3 --no-parent --reject "index.html*" https://webdav.dandiarchive.org/dandisets/000027/releases/0.210831.2033/` is admittedly a wget command, but a pretty exotic one
2. probably the cause of (1) — if I go to https://webdav.dandiarchive.org/dandisets/000027/releases/0.210831.2033/sub-RAT123/ and copy the link for the NWB file, I get https://api.dandiarchive.org/api/assets/1c095f5f-d1e2-45db-b807-fdcfea08c6de/download/ instead of a link to an NWB file

I assume this is all working as expected and there's no feasible way to actually get links to things?
In any case, that's what I meant by “easier” access.

But if this is unavoidable, maybe we could publish that snippet somewhere... where?
We have a copy-click thing on the DANDI website, would be cool to have options, like github has.
If that's too tricky to do... people don't generally read the manual on a website before they use it, I never read the GitHub manual... so in any other place it's likely to be as good as unstated.

**Comment by yarikoptic** [comment]
1. the command is elaborate just to be "very good".  Just take your favorite `wget` invocation to download the folder and apply it here - my bet would be that it would work just as good.
2. yes, it relies on redirects and `wget` follows redirects by default (as opposted to `curl` IIRC)

Overall - only the notion of redirects is specific here (hence target filenames could be effected as well) and a matter of documentation.
